[package]
name = "get_score"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0-rc.0"

[dev-dependencies]
criterion = { version = "0.7.0" }

[[bench]]
name = "benchmark"
harness = false